version: '3.6'

services:
    api:
        build:
            context: ./sensor_api
        container_name: sensor_api
        restart: always
        volumes:
            - "./sensor_api:/api"
        ports:
            - "${API_PORT}:${API_PORT}"
        environment:
            DEBUG: ${DEBUG}
            RELOAD: ${RELOAD}
            API_HOST: ${API_HOST}
            API_PORT: ${API_PORT}
    
    db:
        image: postgres:15.3
        restart: always
        container_name: sensor_db
        environment:
            POSTGRES_DB: sensors
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - 5432:5432
        volumes:
            - ./db:/var/lib/postgresql/data
