FROM python:3.11.3-buster

ENV PYTHONUNBUFFERED=1
ENV DEBIAN_FRONTEND="noninteractive"

WORKDIR /api

COPY ./requirements.txt .

RUN pip install --no-cache-dir --upgrade -r requirements.txt

CMD ["python", "main.py"]
